# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8e83b28f578dc7ccdd5f200ea0143478d0cca396fc0cbb1aa180acd9ddad73bde29348023d49158805344243f4e92fdef1c50014b58488c6b45e41df8b1e6db3

test:
  secret_key_base: 41409926c8d35f98f082d052ead7879d26502332283f19b9088ed08d65627c3dafe8b6cf5c3997539314cf62a2a88624e42a16bd9d17e99d46e5c4d79d1c25df

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
